version: '3.9'

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data

  hybridrag-app:
    build: .
    container_name: hybridrag-app
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=your_openai_key
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
      - VECTOR_DIR=vector_store
      - ARTICLES_FILE=data/oncology_articles_100.json
    depends_on:
      - neo4j
    volumes:
      - ./vector_store:/app/vector_store
      - ./data:/app/data
      - ./subgraphs:/app/subgraphs

  recover-neo4j:
    build: .
    container_name: recover-neo4j
    entrypoint: ["python", "restore_neo4j_from_file.py"]
    depends_on:
      - neo4j
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    volumes:
      - ./data:/app/data
    profiles:
      - recover  # <<< NEW: only runs when explicitly requested

volumes:
  neo4j_data:
