up:
	docker-compose up --build

down:
	docker-compose down

recover:
	docker-compose --profile recover up recover-neo4j

logs:
	docker-compose logs -f

rebuild:
	docker-compose up --build --force-recreate
